import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font } from '@react-pdf/renderer';

// Create styles
const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#FFFFFF',
        padding: 30,
        fontFamily: 'Helvetica',
    },
    header: {
        marginBottom: 20,
        borderBottom: 1,
        borderBottomColor: '#E2E8F0',
        paddingBottom: 10,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1E293B',
    },
    subtitle: {
        fontSize: 12,
        color: '#64748B',
        marginTop: 5,
    },
    section: {
        margin: 10,
        padding: 10,
    },
    issueCard: {
        marginBottom: 15,
        padding: 15,
        borderRadius: 8,
        border: 1,
        borderColor: '#E2E8F0',
    },
    issueTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#1E293B',
        marginBottom: 5,
    },
    issueDetail: {
        fontSize: 10,
        color: '#475569',
        marginBottom: 3,
    },
    severityHigh: {
        color: '#EF4444',
        fontWeight: 'bold',
    },
    severityMedium: {
        color: '#F59E0B',
        fontWeight: 'bold',
    },
    severityLow: {
        color: '#10B981',
        fontWeight: 'bold',
    },
    fixTitle: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#0F172A',
        marginTop: 8,
        marginBottom: 4,
    },
    fixContent: {
        fontSize: 10,
        color: '#334155',
        lineHeight: 1.4,
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 30,
        right: 30,
        textAlign: 'center',
        fontSize: 8,
        color: '#94A3B8',
        borderTop: 1,
        borderTopColor: '#E2E8F0',
        paddingTop: 10,
    }
});

interface SEOReportPDFProps {
    issues: any[];
    projectName: string;
}

export const SEOReportPDF = ({ issues, projectName }: SEOReportPDFProps) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                <Text style={styles.title}>SEO Audit Report</Text>
                <Text style={styles.subtitle}>{projectName} - Generated on {new Date().toLocaleDateString()}</Text>
            </View>

            <View>
                <Text style={{ fontSize: 18, marginBottom: 15, color: '#334155' }}>Recommended Fixes</Text>
                {issues.map((issue, index) => (
                    <View key={index} style={styles.issueCard}>
                        <Text style={styles.issueTitle}>{issue.issueTitle}</Text>
                        <Text style={styles.issueDetail}>
                            Severity: <Text style={
                                issue.severity === 'high' ? styles.severityHigh : 
                                issue.severity === 'medium' ? styles.severityMedium : 
                                styles.severityLow
                            }>{issue.severity.toUpperCase()}</Text>
                        </Text>
                        <Text style={styles.issueDetail}>Category: {issue.category}</Text>
                        
                        <Text style={styles.fixTitle}>Recommended Action:</Text>
                        <Text style={styles.fixContent}>
                            {issue.recommendedFix?.recommendedAction || 'No recommendation available.'}
                        </Text>
                        
                        {issue.recommendedFix?.expectedSEOImpact && (
                            <Text style={[styles.issueDetail, { marginTop: 5 }]}>
                                Expected Impact: {issue.recommendedFix.expectedSEOImpact}
                            </Text>
                        )}
                    </View>
                ))}
            </View>

            <Text style={styles.footer}>
                Generated by SEO Fixer AI - Empowering your web presence.
            </Text>
        </Page>
    </Document>
);
